package com.oa.crm;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CRM service = new CRM();
 * CRMPortType portType = service.getCRMHttpPort();
 * portType.readOAStatus(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CRM", targetNamespace = "webservices.services.weaver.com.cn", wsdlLocation = "http://172.17.10.225//services/CRM?wsdl")
public class CRM extends Service {

	private final static URL CRM_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.oa.crm.CRM.class
			.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.oa.crm.CRM.class.getResource(".");
			url = new URL(baseUrl, "http://172.17.10.225//services/CRM?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://172.17.10.225//services/CRM?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CRM_WSDL_LOCATION = url;
	}

	public CRM(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CRM() {
		super(CRM_WSDL_LOCATION, new QName(
				"webservices.services.weaver.com.cn", "CRM"));
	}

	/**
	 * 
	 * @return returns CRMPortType
	 */
	@WebEndpoint(name = "CRMHttpPort")
	public CRMPortType getCRMHttpPort() {
		return super.getPort(new QName("webservices.services.weaver.com.cn",
				"CRMHttpPort"), CRMPortType.class);
	}

}
